name: 'Venus Globalping GitHub Action'
author: 'Venus Protocol'
description: 'A GitHub Action to ping a website from multiple locations using Globalping'
inputs:
  path:
    description: 'Path of the directory to upload'
    required: true
  pinName:
    description: 'Name of the pin. This name is used to determine what pins to delete when passing "maxPinsToKeep" input' 
    required: true
  maxPinsToKeep:
    description: 'Sets the limit for how many pins with the same name to retain, deleting older ones'
    required: false
  pinataApiKey:
    description: 'Pinata API key. Visit https://docs.pinata.cloud/account-management/api-keys'
    required: true
  pinataSecretApiKey: 
    description: 'Pinata secret API key. Visit https://docs.pinata.cloud/account-management/api-keys'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
